import Head from 'next/head';
import Image from 'next/image';
import { Loading } from '../components';

export default function Home() {
   return (
      <div>
         <Head>
            <title>Home | Dev Movies</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <h1>Dev Movies</h1>
         <Loading />
      </div>
   );
}
